### PR TITLE
Accept Symfony 2.6.x

### PR DESCRIPTION
**Pull request by dizda**

### CODE REVIEW

**Comment by dizda** [comment]
Thanks bro'!

**Comment by JoshuaEstes** [comment]
=) Once I get a few more things in place, this will be getting a lot of updates. Thanks for the patch!

**Comment by dizda** [comment]
What you mean ?

**Comment by JoshuaEstes** [comment]
I'm working on a new project and will need this to support multiple nodes and a few other things.

**Comment by dizda** [comment]
Oh ok, nice :)

**Pull request merged**
